---

- name: Debian | Ensure required packages are installed
  apt:
   name: '{{ mount_packages["Debian"][item.fstype] }}'
   state: 'latest'
  when: (item.fstype is string and item.fstype in ['cifs', 'nfs'])
  with_flattened:
    - mount_list
    - mount_group_list
    - mount_host_list

- name: mount devices
  mount:
   dump: '{{ item.dump|default(omit) }}'
   fstab: '{{ item.fstab|default("/etc/fstab") }}'
   fstype: '{{ item.fstype }}'
   name: '{{ item.dest }}'
   src: '{{ item.src }}'
   opts: '{{ item.opts|default(omit) }}'
   passno: '{{ item.passno|default(omit) }}'
   state: '{{ item.state|default("mounted") }}'
  when: (item.src is string)
  with_flattened:
    - mount_list
    - mount_group_list
    - mount_host_list
