---

- name: Debian | Ensure required packages are installed
  apt:
    name: '{{ mount_packages["Debian"][item.fstype] }}'
    state: 'latest'
  when: (item.fstype is string and item.fstype in ['cifs', 'nfs'])
  with_flattened:
    - mount_list
    - mount_group_list
    - mount_host_list
