---
- name: Check for supported operating system on target
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: ansible_os_family not in ['Debian']

- name: Include Debian specific tasks
  include: Debian.yml
  when: mount is defined and ansible_os_family == 'Debian'

# ToDo
#
#- name: Include RedHat specific tasks
#  include: RedHat.yml
#  when: ansible_os_family == 'RedHat'
#
#- name: Include Suse specific tasks
#  include: Suse.yml
#  when: ansible_os_family == 'Suse'
